- name: Install packages
  sudo: yes
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
      # Database
      - postgresql
      - libpq-dev # Required for Ansible to interact with postgres
      - python-psycopg2 # Required for Ansible to interact with postgres

      # Python Dev
      - python-dev
      - python-setuptools
      - python-virtualenv

      # build tools + essential
      - make
      - curl
      - tree
      - build-essential
      - libssl-dev
      - golang
      - git-core

- name: Allow password authentication for local socket users
  sudo: yes
  copy: src=pg_hba.conf dest=/etc/postgresql/9.1/main/pg_hba.conf force=yes
  notify:
      - Restart Postgres

- name: Create Database
  sudo: yes
  sudo_user: postgres
  postgresql_db: name={{ db_name }}

- name: Create User
  sudo: yes
  sudo_user: postgres
  postgresql_user: name={{ db_user }} password={{ db_password }} state=present role_attr_flags=NOSUPERUSER,CREATEDB

- name: Provide user with DB permissions
  sudo: yes
  sudo_user: postgres
  postgresql_user: user={{ db_user }} db={{ db_name }} priv=ALL

- name: clean git directory  
  file: path=/home/vagrant/git/ state=absent

- name: add git repos
  git: repo={{ item.repo }}
        dest=/home/vagrant/git/{{ item.name }}
        accept_hostkey=True
  with_items:
    - {name: 'episode47', repo: 'https://github.com/jweissig/episode-47.git'}
    - {name: 'z', repo: 'https://github.com/mjgil/z.git'}
    - {name: 'dotfiles', repo: 'https://github.com/mjgil/dotfiles.git'}
    # - git@bitbucket.org:mjgil/d3.git

- name: rm bashrc
  file: path=/home/vagrant/.bashrc state=absent

- name: copy bashrc from dotfiles
  file: src=/home/vagrant/git/dotfiles/.bashrc dest=/home/vagrant/.bashrc state=link